
    create table exams (
        deadline date,
        id bigint generated by default as identity,
        status bigint check ((status in (0,1,2))),
        description varchar(255),
        primary key (id)
    );

    create table group_projects (
        deadline date,
        id bigint generated by default as identity,
        status bigint check ((status in (0,1,2))),
        description varchar(255),
        my_role varchar(255),
        primary key (id)
    );

    create table topics (
        exam_id bigint,
        id bigint generated by default as identity,
        proficiency bigint check ((proficiency in (0,1,2))),
        description varchar(255),
        primary key (id)
    );

    alter table if exists topics 
       add constraint FK5ev6xmksptiooaygsp0bjio5j 
       foreign key (exam_id) 
       references exams;
INSERT INTO group_projects(description, deadline, my_role, status) VALUES     ('Trabalho A1 - Semana Acadêmica', '2026-02-01', 'Pesquisar',0),     ('Trabalho A2 - Apresentação', '2026-03-01', 'Canvas',0);
INSERT INTO exams(description, deadline, status) VALUES     ('Prova de Cálculo I', '2026-02-01', 0),     ('Prova de Cálculo I A2', '2026-03-01', 0);
INSERT INTO topics(description, proficiency, exam_id) VALUES     ('Derivadas', 0, 1),     ('Integrais', 0, 1);
