@startuml

enum Status {
    GUARANTEED
    NEED_GRADE
    FIFTY_FIFTY
}

enum Proficiency {
    KNOW_IT_WELL
    KNOW_NOTHING
    ' mais-ou-menos
    SO_SO
}

abstract class Commitment {
    id: Long
    deadline: LocalDate
    description: String
}

class Exam extends Commitment {
    topics: List<Topic>
    status: Status
}

class Topic {
    proficiency: Proficiency
    description: String
}

class Assignment extends Commitment {
    myRole: String
    status: Status
}

Exam -- Topic

@enduml