# o app de mangas lá tá ocupando a porta
%dev.quarkus.http.port=8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=piau
quarkus.datasource.password=123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/piaudb

%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

%dev.quarkus.hibernate-orm.log.sql=true

%dev.quarkus.hibernate-orm.scripts.generation=drop-and-create
%dev.quarkus.hibernate-orm.scripts.generation.create-target=create.sql
%dev.quarkus.hibernate-orm.scripts.generation.drop-target=drop.sql

